define('map', ['types'], function(types) {
    var WALL = types.WALL;
    var PLY1 = {
        type: types.PLAYER,
        id: 0
    };
    var PLY2 = {
        type: types.PLAYER,
        id: 1
    };
    var PLY3 = {
        type: types.PLAYER,
        id: 2
    };
    var DEBR = types.DEBREE;
    var MOTH = types.MOTHERSHIP;
    var SPW1 = {
        type: types.SPAWN,
        id: 0
    };
    var SPW2 = {
        type: types.SPAWN,
        id: 1
    };
    var SPW3 = {
        type: types.SPAWN,
        id: 2
    };
    var FLYE = types.FLYER;
    var GRUN = types.GRUNT;
    var SHIE = types.SHIELDMAN;
    var MINE = types.MINE;
    var PUNC = types.PUNCH;
    var TURR = types.TURRET;
    var SHOT = types.SHOT;
    var MISH = types.MINESHELL;
    var PAR1 = {
        type: types.PART,
        id: 0
    };
    var PAR2 = {
        type: types.PART,
        id: 1
    };
    var PAR3 = {
        type: types.PART,
        id: 2
    };

    // W    - Waypoint type
    // (a)  - Spawn point index
    // G/F  - Enemy type, (G)runt/(F)lyer
    // (b)  - Index
    var W1G0 = "W1G0";
    var W1G1 = "W1G1";

    var W2G0 = "W2G0";
    var W2G1 = "W2G1";
    var W2G2 = "W2G2";

    var W3G0 = "W3G0";
    var W3G1 = "W3G1";

    var W1F0 = "W1F0";
    var W1F1 = "W1F1";
    
    var W2F0 = "W2F0";
    
    var W3F0 = "W3F0";

    return {
        map: [
            [WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,PAR1,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,PAR2,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,W1F0,/**/,/**/,WALL,/**/,DEBR,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,DEBR,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,DEBR,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,W1F1,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,DEBR,/**/,DEBR,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,DEBR,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,W3F0,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,SPW3,WALL],
            [WALL,/**/,/**/,/**/,/**/,DEBR,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,WALL,WALL,WALL,WALL,WALL,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,PLY1,/**/,/**/,PLY3,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,MOTH,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,W1G0,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,W3G1,/**/,/**/,/**/,/**/,/**/,/**/,/**/,W3G0,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,W2F0,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,WALL,WALL,WALL,WALL,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,DEBR,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,DEBR,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,DEBR,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,DEBR,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,DEBR,/**/,SPW1,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,PAR2,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,DEBR,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,SPW2,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL],
        ],
        waypointCollections: {
            gruntSpawns: [
                [W1G0],
                [],
                [W3G0, W3G1],
            ],
            flyerSpawns: [
                [W1F0, W1F1],
                [W2F0],
                [W3F0],
            ]
        },
        waves: [
            { duration: 0 },
            { spawnIdx: 0, type: types.GRUNT },
            { duration: 10 },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 10 },
            { spawnIdx: 1, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 10 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 7 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 7 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 7 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 12 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 12 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 12 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 16 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
        ]
    }
    
});