define('map', [], function() {
    var WALL = "Wall";
    var PLAY = "Player";
    var PLY1 = "Player1";
    var PLY2 = "Player2";
    var PLY3 = "Player3";
    var DEBR = "Debree";
    var MOTH = "Mothership";
    var SPAW = "Spawn";
    var SPW1 = "Spawn1";
    var SPW2 = "Spawn2";
    var SPW3 = "Spawn3";
    var PART = "Part";
    var ENEM = "Enemy";
    var FLYE = "Flyer";
    var GRUN = "Grunt";
    var SHIE = "Shieldman";
    var MINE = "Mine";
    var PUNC = "Punch";
    var TURRET = "Turret";
    var SHOT = "Shot";
    var MISH = "Mineshell";
    var PAR1 = "Part1";
    var PAR2 = "Part2";
    var PAR3 = "Part3";

    // W    - Waypoint type
    // (a)  - Spawn point index
    // G/F  - Enemy type, (G)runt/(F)lyer
    // (b)  - Index
    var W1G0 = "W1G0";
    var W1G1 = "W1G1";

    var W2G0 = "W2G0";
    var W2G1 = "W2G1";
    var W2G2 = "W2G2";

    var W3G0 = "W3G0";
    var W3G1 = "W3G1";

    var types = { 
        WALL: WALL,
        PLAYER: PLAY,
        PLAYER1: PLY1,
        PLAYER2: PLY2,
        PLAYER3: PLY3,
        DEBREE: DEBR,
        MOTHERSHIP: MOTH,
        SPAWN: SPAW,
        SPAWN1: SPW1,
        SPAWN2: SPW2,
        SPAWN3: SPW3,
        PART: PART,
        FLYER: FLYE,
        GRUNT: GRUN,
        SHIELDMAN: SHIE,
        MINE: MINE,
        PUNCH: PUNC,
        TURR: TURRET,
        SHOT: SHOT,
        MINESHELL: MISH,
        PART1: PAR1,
        PART2: PAR2,
        PART3: PAR3
    };
    return {
        types: types,
        map: [
            [WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,PAR1,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,PAR2,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,DEBR,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,DEBR,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,DEBR,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,DEBR,/**/,DEBR,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,DEBR,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,SPW3,WALL],
            [WALL,/**/,/**/,/**/,/**/,DEBR,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,W1G1,WALL,WALL,WALL,WALL,WALL,WALL,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,PLY2,/**/,/**/,PLY1,/**/,/**/,PLY3,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,SPW1,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,MOTH,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,W1G0,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,W2G2,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,W3G1,/**/,/**/,/**/,/**/,/**/,/**/,/**/,W3G0,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,WALL,WALL,WALL,WALL,WALL,/**/,W2G1,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,DEBR,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,DEBR,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,W2G0,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,DEBR,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,DEBR,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,/**/,DEBR,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,PAR3,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,DEBR,/**/,WALL],
            [WALL,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,SPW2,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,/**/,WALL],
            [WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL],
        ],
        waypointCollections: {
            gruntSpawns: [
                [W1G0, W1G1],
                [W2G0, W2G1, W2G2],
                [W3G0, W3G1],
            ]
        },
        waves: [
            { duration: 10 },
            { spawnIdx: 0, type: types.GRUNT },
            { duration: 10 },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 10 },
            { spawnIdx: 1, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 10 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 7 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 7 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 7 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 12 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 16 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 5 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 3 },
            { spawnIdx: 0, type: types.FLYER },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.FLYER },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.FLYER },
            { spawnIdx: 2, type: types.GRUNT },
            { duration: 4 },
            { spawnIdx: 0, type: types.GRUNT },
            { spawnIdx: 1, type: types.GRUNT },
            { spawnIdx: 2, type: types.GRUNT },
        ]
    }
    
});